### ISSUE TITLE
Next Team: please add your own GitHub Access Token

### ISSUE THREAD

**Issue by Nef10** [HPI-SWA-Teaching/SWT15-Project-03#128]
For testing on Travis CI a GitHub login ley (as described in the Development section of the README) needs to be committed and pushed (encrypted via the Travis CLI).

It would be nice if you change this token to one of your tokens (or create an extra user for this).

**Comment by cmfcmf** [comment]
This has been done in https://github.com/HPI-SWA-Teaching/SWT16-Project-05/issues/7.
